jobs:
  include:
    - stage: Build Frontend
      language: node_js
      node_js: 14
      script:
        - cd front
        - npm install
        - npm run build

    - stage: Build Backend
      language: go
      go: 1.12.x
      before_install:
      - go get github.com/gobuffalo/packr/packr
      - packr
      install:
      - go get -t -v ./...
      script:
      - export GIT_VERSION=`git describe --tags`
      - printf "package version\n\n// Current gets the current application version\nconst Current = \"%s\"\n" "$GIT_VERSION" > pkg/version/current.go
      - diff -u <(echo -n) <(gofmt -d .)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -v -race ./...

    - stage: Create App
      language: go
      go: 1.12.x
      before_install:
      - go get github.com/mitchellh/gox
      script:
      - gox -osarch="linux/arm linux/amd64 windows/amd64 windows/386 darwin/amd64" -output="potatorrent.{{.OS}}.{{.Arch}}"
        -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...

    - stage: Deploy
      script: skip
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: L2Z+a2mAbHANeZa2U7IkhnSsa3f/KygPwwTjYym2+vrXiaTqdaJJ+2FuBVa3JoZ32CH2lwctPK+WtqDNRQHBKgaY+WYTQz2/I1gChRKXmhOy4zazeWK6qbIw88n4K1B/9IUA6Efz44AhpPDapXh+YpROZhzgDi3Fdl7bUuPYJ/6ghlnLjBsPDS9+rtOJW+ssbXzkrE24oqbabgG7QlE01NjDcpQ/268zU5Tn682bRHOKbcnIp9lhrdinvKnQXdhZA/2kVjSn66VSSsWRtE6Xp//d+8TPIZGWo1JiIWL8RiU07jPhjvytlDZUgTT7LKamq5Cq6eHK11J67TWUd7i1MX3XgzTNFKn2AlbWJY1zA+xfokpVpCZNjNy4dp/65BBVHQzSrIhqGTbz5h6whxydcRoxWSXnMLn7ToFAE3IZ9hHG9+p193/MenrvS/kGw2My6iymXypqAGr2N252mgkDw7j9rNi9kaiDYWgE/0dmQVAGLOcWarwt5DWCRukQKzBHq3NlaX12xBHyPb/rCWJUn3oqBRVvIv73P7Zn2QVyhFP6vtquO33uI1jgwuua+X2I/6C2XDDRE5Pxz5REq3rRYhBaMn82hQMXvwoqXpH6dTyo4WMqK0l0Ms/RHDvVcy4xRC+y3F//9ODEuHAc/XsoTbFmA6Pv/AFfsNOyv2taj1g=
        file: 
        - potatorrent.windows.amd64.exe
        - potatorrent.windows.386.exe
        - potatorrent.darwin.amd64
        - potatorrent.linux.amd64
        - potatorrent.linux.arm
        on:
          tags: true
          repo: nilbelec/potatorrent
