name: Potatorrent CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build Frontend
        run: |
          cd ./src/github.com/${{ github.repository }}/front
          npm install
          npm run build

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.x

      - name: Build Backend
        run: |
          cd ./src/github.com/${{ github.repository }}
          go get github.com/gobuffalo/packr/packr
          packr
          go get -t -v ./...
          export GIT_VERSION=`git describe --tags`
          printf "package version\n\n// Current gets the current application version\nconst Current = \"%s\"\n" "$GIT_VERSION" > pkg/version/current.go
          go vet $(go list ./... | grep -v /vendor/)
          go test -v -race ./...
          go get github.com/mitchellh/gox
          mkdir artifacts
          gox -osarch="linux/arm linux/amd64 windows/amd64 windows/386 darwin/amd64" -output="artifacts/potatorrent.{{.OS}}.{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: potatorrent
          path: ./src/github.com/${{ github.repository }}/artifacts/*
